const path = require('path');

export const songs = [
  {
    id: 0,
    title: 'She will be Loved',
    artist: 'Maroon5',
    genre: 'POP',
    artwork: require('./assets/image/image1.jpeg'),
    url: require('./assets/audio/song1.mp3'),
  },
  {
    id: 1,
    title: 'Sugar',
    artist: 'Maroon5',
    genre: 'POP',
    artwork: require('./assets/image/image2.jpeg'),
    url: require('./assets/audio/song2.mp3'),
  },
  {
    id: 2,
    title: '제목3',
    artist: '가수3',
    genre: '시티팝',
    artwork: require('./assets/image/image3.jpeg'),
    url: require('./assets/audio/song3.mp3'),
  },
  {
    id: 3,
    title: '제목4',
    artist: '가수4',
    genre: '시티팝',
    artwork: require('./assets/image/image4.jpeg'),
    url: require('./assets/audio/song4.mp3'),
  },
  {
    id: 4,
    title: '제목5',
    artist: '가수5',
    genre: '시티팝',
    artwork: require('./assets/image/image5.jpeg'),
    url: require('./assets/audio/song5.mp3'),
  },
  {
    id: 5,
    title: '제목6',
    artist: '가수6',
    genre: '시티팝',
    artwork: require('./assets/image/image6.jpeg'),
    url: require('./assets/audio/song6.mp3'),
  },
  {
    id: 6,
    title: '제목7',
    artist: '가수7',
    genre: '시티팝',
    artwork: require('./assets/image/image7.jpeg'),
    url: require('./assets/audio/song7.mp3'),
  },
  {
    id: 7,
    title: '제목8',
    artist: '가수8',
    genre: '시티팝',
    artwork: require('./assets/image/image8.jpeg'),
    url: require('./assets/audio/song8.mp3'),
  },
  {
    id: 8,
    title: '제목9',
    artist: '가수9',
    genre: '시티팝',
    artwork: require('./assets/image/image9.jpeg'),
    url: require('./assets/audio/song9.mp3'),
  },
  {
    id: 9,
    title: '제목10',
    artist: '가수10',
    genre: '시티팝',
    artwork: require('./assets/image/image10.jpeg'),
    url: require('./assets/audio/song10.mp3'),
  },
  {
    id: 10,
    title: '제목11',
    artist: '가수11',
    genre: '시티팝',
    artwork: require('./assets/image/image11.jpeg'),
    url: require('./assets/audio/song11.mp3'),
  },

  {
    id: 11,
    title: '제목12',
    artist: '가수12',
    genre: '시티팝',
    artwork: require('./assets/image/image12.jpeg'),
    url: require('./assets/audio/song12.mp3'),
  },

  {
    id: 12,
    title: '제목13',
    artist: '가수13',
    genre: '시티팝',
    artwork: require('./assets/image/image13.jpeg'),
    url: require('./assets/audio/song13.mp3'),
  },
  {
    id: 13,
    title: '제목14',
    artist: '가수14',
    genre: '시티팝',
    artwork: require('./assets/image/image14.jpeg'),
    url: require('./assets/audio/song14.mp3'),
  },
  {
    id: 14,
    title: '제목15',
    artist: '가수15',
    genre: '시티팝',
    artwork: require('./assets/image/image15.jpeg'),
    url: require('./assets/audio/song15.mp3'),
  },
];
